feat(node): integrated pagination for devices list view
infinimesh/infinimesh pull request #671
Opened 2024-01-30 15:37 UTC by vladimirnikolic509

Fixes #590

2024-01-30 21:15 UTC, slntopp requested changes
I suggest to add Count method/field as well, so we don't have unlimited amout of pages 

Additionally, as a part of ongoing refactoring and refinement, please provide unit tests for `ListQuery` and update `DevicesService.List` tests to cover the pagination functionality

2024-01-30 21:15 UTC, slntopp commented on pkg/graph/devices.go
> +		ctx = WithSkip(ctx, (int(page)-1)*int(limit))
Should be named WithOffset

2024-01-30 21:15 UTC, slntopp commented on pkg/graph/common.go
> +const listObjectsOfKindWithPagination = `
it'd be better to embed `LIMIT` clause into the query same way as it's done with Namespace filter

2024-02-02 11:37 UTC, vladimirnikolic509 commented on pkg/graph/devices.go
> +		ctx = WithSkip(ctx, (int(page)-1)*int(limit))
Fixed

2024-02-02 11:37 UTC, vladimirnikolic509 commented on pkg/graph/common.go
> +const listObjectsOfKindWithPagination = `
Fixed

2024-02-02 19:15 UTC, slntopp requested changes
I think count doesn't worth a separate query, Arango should be using lazy queries, so you can probably just get them all and then slice the page out of the result without any or big performance overhead

2024-02-05 15:11 UTC, slntopp requested changes

2024-02-05 15:11 UTC, slntopp commented on pkg/graph/devices.go
> +	if limit > 0 && page > 0 {
this condition should be part of the query, i.e. the query goes like

1. Get all accessible devices
2. `LET count = COUNT(result)`
3. `%s` add pagination here if requested
4. RETURN { result, count }

2024-02-05 15:11 UTC, slntopp commented on pkg/graph/devices.go
> +		// Total:   len(r),
and with accordance to the previous comment, total should be returned

2024-02-05 15:11 UTC, slntopp commented on pkg/graph/devices_test.go
> +func TestList_Error_1(t *testing.T) {
Name tests like `TestFunction_FailsOn_WhatItisFailingOn`
For example this test could be named `TestList_FailsOn_ListQuery`

2024-02-05 15:11 UTC, slntopp commented on pkg/graph/devices.go
> +	if limit > 0 && page > 0 {
So it should be part of `ListQuery` logic

2024-02-05 15:20 UTC, vladimirnikolic509 commented on pkg/graph/devices.go
> +	if limit > 0 && page > 0 {
Then we will have to move the logic of reading from cursor too on ListQuery. @slntopp

2024-02-05 16:03 UTC, slntopp commented on pkg/graph/devices.go
> +	if limit > 0 && page > 0 {
Why is that?

2024-02-05 16:05 UTC, slntopp commented on pkg/graph/devices.go
> +	if limit > 0 && page > 0 {
Pagination should be implemented inside the AQL query, same as filter, so cursor can stay where-ever it is right now. 

Ideally ofcourse we could introduce generic, but Protobuf structures don't provide `Set` methods unfortunately

2024-02-05 16:11 UTC, vladimirnikolic509 commented on pkg/graph/devices.go
> +	if limit > 0 && page > 0 {
https://github.com/infinimesh/infinimesh/pull/671#pullrequestreview-1860136750
> I think count doesn't worth a separate query, Arango should be using lazy queries, so you can probably just get them all and then slice the page out of the result without any or big performance overhead

You said to use single query and then get total count from it, and slice the result as per sent value of limit/page. At least that’s what I understood.
Then if I am to return count from ListQuery itself, how do I return count from ListQuery without reading from cursor in ListQuery function itself?
@slntopp

2024-02-05 16:31 UTC, slntopp commented on pkg/graph/devices.go
> +	if limit > 0 && page > 0 {
You can do it all withing AQL as i've described in the first comment of this thread.
Your base query would be smth like this:

```aql
LET result = (
FOR node, edge, path IN 0..@depth OUTBOUND @from
GRAPH @permissions_graph
OPTIONS {order: "bfs", uniqueVertices: "global"}
FILTER IS_SAME_COLLECTION(@@kind, node)
FILTER edge.level > 0
%s
    LET perm = path.edges[0]
    LET last = path.edges[-1]
	RETURN MERGE(node, {
	    uuid: node._key,
	    access: {
	        level: last.role == 2 ? last.level : perm.level,
	        role:  last.role == 2 ? last.role : perm.role,
	        namespace: last.role == 2 ? null : path.vertices[-2]._key
	     }
	    }
    )
)

LET count = LENGTH(result)

%s
```

And the second `%s` would be replaced with `RETURN {result, count}` by default. Unless, there are pagination parameters provided, then you would replace it with smth like:

```aql
LET paginated = SLICE(result, offset, offset + page_length)
RETURN {result: paginated, count}
```

Please manually test the queries with the local or dev ArangoDB deployment

2024-02-05 16:32 UTC, slntopp commented on pkg/graph/devices.go
> +	if limit > 0 && page > 0 {
> note on this, would be great to replace simple fmt.Sprintf with some sort of templating or at least named replacements.

2024-02-05 16:35 UTC, slntopp commented on pkg/graph/devices.go
> +	if limit > 0 && page > 0 {
> Another note, you can use lazy evaluation to define this condition, like 
```
RETURN { 
 result: offset != NULL && limit != NULL ? SLICE(...) : result,
 count
}
```

2024-02-07 17:25 UTC, vladimirnikolic509 commented on pkg/graph/devices.go
> +	if limit > 0 && page > 0 {
Fixed

2024-02-07 17:26 UTC, vladimirnikolic509 commented on pkg/graph/devices_test.go
> +func TestList_Error_1(t *testing.T) {
Fixed

2024-02-07 17:26 UTC, vladimirnikolic509 commented on pkg/graph/devices.go
> +		// Total:   len(r),
Fixed

2024-02-12 18:52 UTC, slntopp commented
- Created a separate GenericRepo for ListQuery and other CRUD operations in the future.
- Updated tests
- Fixed AQL Query to make it possible to limit result with 0 offset

2024-02-12 18:58 UTC, slntopp commented
- renamed field `page` -> `offset`

2024-02-12 18:58 UTC, slntopp approved these changes

2024-02-12 19:01 UTC, merged