Resolve #670: bug: timestamppb conversion at connection state
infinimesh/infinimesh pull request #679
Opened 2024-02-02 09:25 UTC by SazukinPavel

2024-02-02 11:41 UTC, vladimirnikolic509 approved these changes

2024-02-02 19:18 UTC, slntopp requested changes

2024-02-02 19:18 UTC, slntopp commented on console/src/components/devices/device_card/status-corner.vue
> +        if (timestamp) {
Useless condition, since you have `.? ||` clause, timestamp will always be not `null`

2024-02-02 19:18 UTC, slntopp commented on console/src/components/devices/device_card/status-corner.vue
> +            let d = new Date(timestamp)
Since you're using `toDate()` method above - useless type casting

2024-02-05 10:51 UTC, SazukinPavel commented on console/src/components/devices/device_card/status-corner.vue
> +            let d = new Date(timestamp)
i expect timestamp as number or rpc  Timestamp type. number requires casting. and also props.connection.timestamp can be null, so so this expression also will be wrong:
props.connection.timestamp?.toDate() || new Date(props.connection.timestamp) 

so I don't see a better option than this

2024-02-05 10:54 UTC, SazukinPavel commented on console/src/components/devices/device_card/status-corner.vue
> +        if (timestamp) {
timestamp may be null. at least for now, so this check makes sense

2024-02-06 09:07 UTC, slntopp approved these changes

2024-02-06 11:08 UTC, merged